source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sass-rails', '~> 4.0.3'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'
gem 'sdoc', '~> 0.4.0',  group: :doc

group :development, :test do
  gem 'spring'
  gem 'rspec-rails'
  gem "pry"
end
